export const videoData = [
  {
    id: 1,
    title: "Amake akti golpo diben please",
    thumbnail: "/images/amake-akti-golpo-diben-please.png",
    videoUrl: "https://example.com/amake-akti-golpo-diben-please.mp4",
  },
  {
    id: 2,
    title: "Dushmon Khotom",
    thumbnail: "/images/dushmon-khotom.png",
    videoUrl: "https://example.com/dushmon-khotom.mp4",
  },
  {
    id: 3,
    title: "Iccha Kore Na",
    thumbnail: "/images/iccha-kore-na.png",
    videoUrl: "https://example.com/iccha-kore-na.mp4",
  },
  {
    id: 4,
    title: "Kopa Shamshu",
    thumbnail: "/images/kopa-shamshu.png",
    videoUrl: "https://example.com/kopa-shamshu.mp4",
  },
  {
    id: 5,
    title: "Local Jamai",
    thumbnail: "/images/local-jamai.png",
    videoUrl: "https://example.com/local-jamai.mp4",
  },
  {
    id: 6,
    title: "Made in Bangladesh",
    thumbnail: "/images/made-in-bangladesh.png",
    videoUrl: "https://example.com/made-in-bangladesh.mp4",
  },
  {
    id: 7,
    title: "Mukher Shorgo",
    thumbnail: "/images/mukher-shorgo.png",
    videoUrl: "https://example.com/mukher-shorgo.mp4",
  },
  {
    id: 8,
    title: "Ogochalo Valobasha",
    thumbnail: "/images/ogochalo-valobasha.png",
    videoUrl: "https://example.com/ogochalo-valobasha.mp4",
  },
  {
    id: 9,
    title: "Osukh",
    thumbnail: "/images/osukh.png",
    videoUrl: "https://example.com/osukh.mp4",
  },
  {
    id: 10,
    title: "Polatok",
    thumbnail: "/images/polatok.png",
    videoUrl: "https://example.com/polatok.mp4",
  },
  {
    id: 11,
    title: "Sodh",
    thumbnail: "/images/sodh.png",
    videoUrl: "https://example.com/sodh.mp4",
  },
  {
    id: 12,
    title: "Sompai Agency",
    thumbnail: "/images/sompai-agency.png",
    videoUrl: "https://example.com/sompai-agency.mp4",
  },
  {
    id: 13,
    title: "Tin Tekka",
    thumbnail: "/images/tin-tekka.png",
    videoUrl: "https://example.com/tin-tekka.mp4",
  },
  {
    id: 14,
    title: "Tomar Amar Biye",
    thumbnail: "/images/tomar-amar-biye.png",
    videoUrl: "https://example.com/tomar-amar-biye.mp4",
  },
  {
    id: 15,
    title: "Tumi Railline",
    thumbnail: "/images/tumi-railline.png",
    videoUrl: "https://example.com/tumi-railline.mp4",
  },
  {
    id: 16,
    title: "Ural Prem",
    thumbnail: "/images/ural-prem.png",
    videoUrl: "https://example.com/ural-prem.mp4",
  },
  {
    id: 17,
    title: "Amake akti golpo diben please",
    thumbnail: "/images/amake-akti-golpo-diben-please.png",
    videoUrl: "https://example.com/amake-akti-golpo-diben-please.mp4",
  },
  {
    id: 18,
    title: "Dushmon Khotom",
    thumbnail: "/images/dushmon-khotom.png",
    videoUrl: "https://example.com/dushmon-khotom.mp4",
  },
  {
    id: 19,
    title: "Iccha Kore Na",
    thumbnail: "/images/iccha-kore-na.png",
    videoUrl: "https://example.com/iccha-kore-na.mp4",
  },
  {
    id: 20,
    title: "Kopa Shamshu",
    thumbnail: "/images/kopa-shamshu.png",
    videoUrl: "https://example.com/kopa-shamshu.mp4",
  },
  {
    id: 21,
    title: "Local Jamai",
    thumbnail: "/images/local-jamai.png",
    videoUrl: "https://example.com/local-jamai.mp4",
  },
  {
    id: 22,
    title: "Made in Bangladesh",
    thumbnail: "/images/made-in-bangladesh.png",
    videoUrl: "https://example.com/made-in-bangladesh.mp4",
  },
  {
    id: 23,
    title: "Mukher Shorgo",
    thumbnail: "/images/mukher-shorgo.png",
    videoUrl: "https://example.com/mukher-shorgo.mp4",
  },
  {
    id: 24,
    title: "Ogochalo Valobasha",
    thumbnail: "/images/ogochalo-valobasha.png",
    videoUrl: "https://example.com/ogochalo-valobasha.mp4",
  },
  {
    id: 25,
    title: "Osukh",
    thumbnail: "/images/osukh.png",
    videoUrl: "https://example.com/osukh.mp4",
  },
  {
    id: 26,
    title: "Polatok",
    thumbnail: "/images/polatok.png",
    videoUrl: "https://example.com/polatok.mp4",
  },
  {
    id: 27,
    title: "Sodh",
    thumbnail: "/images/sodh.png",
    videoUrl: "https://example.com/sodh.mp4",
  },
  {
    id: 28,
    title: "Sompai Agency",
    thumbnail: "/images/sompai-agency.png",
    videoUrl: "https://example.com/sompai-agency.mp4",
  },
  {
    id: 29,
    title: "Tin Tekka",
    thumbnail: "/images/tin-tekka.png",
    videoUrl: "https://example.com/tin-tekka.mp4",
  },
  {
    id: 30,
    title: "Tomar Amar Biye",
    thumbnail: "/images/tomar-amar-biye.png",
    videoUrl: "https://example.com/tomar-amar-biye.mp4",
  },
  {
    id: 31,
    title: "Tumi Railline",
    thumbnail: "/images/tumi-railline.png",
    videoUrl: "https://example.com/tumi-railline.mp4",
  },
  {
    id: 32,
    title: "Ural Prem",
    thumbnail: "/images/ural-prem.png",
    videoUrl: "https://example.com/ural-prem.mp4",
  },
];
